### ISSUE TITLE
Depracated module

### ISSUE THREAD

**Issue by ktavabi** [ktavabi/genz#3]
`_get_hpi_info` not in `mne.chpi`

[mnefun] mnefun/_sss.py (Line 19)

```

_get_hpi_info
```

[Open in IDE](https://api.codestream.com/c/YBtNEotjDWL9G1o4/MRc2_GAsQjWHeDnoCR2AgQ?marker=60949f4f8cffbf37497831d1&ide=default&src=GitHub) · [Open on GitHub](https://github.com/labsn/mnefun/blob/d0763288dbaa3aea8e6aa8cd341e24ee29e9a231/mnefun/_sss.py#L19)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by larsoner** [comment]
Closing for https://github.com/LABSN/mnefun/issues/341
