### ISSUE TITLE
ENH: Add z-coh code

### ISSUE THREAD

**Issue by larsoner** [ktavabi/genz#4]
I don't know what `z-coh` is off-hand but I think computing cross-coupling modulation index `MI` between our ROI AECs could be useful. That would allow us to compare PACs across states and networks. Is that something you can do? Because I don't want to wait on code from anyone. 

EDIT: especially code from this dude...

> In this measure, the principal condition (Deviant, a total of50 trials per participant) is normalized with respect to a baseline condition (Standard, a total of 160 tri-als per participant), which addresses the bias [e.g.,[Khan](https://onlinelibrary.wiley.com/doi/abs/10.1002/aur.1714) et al., 2013].

Then I think if you want to try classification then I would suggest PAC and shortest-path as features for classification into standardized personality (big-5) bins. Thoughts?

_Originally posted by @ktavabi in https://github.com/ktavabi/genz/issues/2#issuecomment-833089739_

**Comment by ktavabi** [comment]
As promised... effective connectivity response measurements in adolescent brains (N=108)

Network **degree-connectivity** and TODO shortest path (laplacian) [Ginset] across brain regions (444 ROIs) resonating in unison for five minutes of elicited _rest_- and _task_ examination states are both derived from the correlations between ongoing signal power for envelopes of synchronous narrow-band activity in extant neural ensembles [Hipp et al]. #star

###   Resting 𝜷 (13-29 Hz; 300sec.)
![image](https://user-images.githubusercontent.com/4381290/118889041-5f264d80-b8b1-11eb-8558-230acff4193a.png)

###  Task 𝜷 (13-29 Hz; 300sec., A/V implicit learning)
![image](https://user-images.githubusercontent.com/4381290/118889068-68171f00-b8b1-11eb-828d-71c6b68a647a.png)

**Comment by larsoner** [comment]
Replicated task!

![task-beta-nxDegree-group-roi](https://user-images.githubusercontent.com/2365790/120029011-7fe25780-bfc3-11eb-9f40-7643229a9da3.png)

Slight coloration differences are presumably due to me using old preprocessed files rather than newer ones. I'm glad it's so robust to it.

Let me know if you (still) want or need help with Hotelling, z-coh, etc. implementations. I need to read Sheraz's paper(s) at some point...

**Comment by ktavabi** [comment]
> Let me know if you (still) want or need help with Hotelling, z-coh, etc. implementations. I need to read Sheraz's paper(s) at some point...

Please implement z-coh. I will look into the Hotelling b/c I also need to verify it's actually different from the multivariate t-testing routine in bad baby: [t-circ](https://github.com/ktavabi/badbaby/blob/efd0a6beef96dec1d6d21da1c5cc87a989e6cfe3/badbaby/python/write_subject_TFRs.py#L36)

**Comment by larsoner** [comment]
Hotelling T2 uses a covariance matrix inversion, looks like t-circ just uses the inverse of the mean of the variances

**Comment by larsoner** [comment]
@ktavabi looks like z-coh is a different measure entirely, involving spectral coherence rather than amplitude envelope correlations. I'd rather stick with AEC and derivative measures for now, since they seem to yield the most reproducible results, rather than move to using measures based on spectral coherence. If you agree I say we close this and see how far we get with AEC

**Comment by ktavabi** [comment]
Agreed.
