### ISSUE TITLE
String handling

### ISSUE THREAD

**Issue by ktavabi** [ktavabi/genz#5]
How does `get_raws_fnames` manage to drop `subject` in the returned list?

```[`faces_learn_01_allclean_fil80_raw_sss.fif', 'thumbs_learn_01_allclean_fil80_raw_sss.fif', 'emojis_learn_01_allclean_fil80_raw_sss.fif', 'faces_test_01_allclean_fil80_raw_sss.fif',
'thumbs_test_01_allclean_fil80_raw_sss.fif',
'emojis_test_01_allclean_fil80_raw_sss.fif']```

[genz] genz/processing/write_roi-aec_frames.py ([Lines 80-81](https://github.com/ktavabi/genz/blob/16e4069f1ecf0511afe13383dac184c69b8ba5b6/genz/processing/write_roi-aec_frames.py#L80))

```

        raws = get_raw_fnames(p, subject, which='pca')

```

[Open in IDE](https://api.codestream.com/c/YBtNEotjDWL9G1o4/OGcpue3ySw637tfuUhAFuQ?marker=609b348f3a7894058f45282a&ide=default&src=GitHub) · [Open on GitHub](https://github.com/ktavabi/genz/blob/0940afdd90e576ce856695a89140f240af29a5b0/genz/processing/write_roi-aec_frames.py#L80-L81)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by larsoner** [comment]
You are missing a `%s_` in front of these strings:

https://github.com/ktavabi/genz/blob/16e4069f1ecf0511afe13383dac184c69b8ba5b6/genz/processing/write_roi-aec_frames.py#L65-L66
